import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Preview from '../components/Preview'

const Home: NextPage = () => {
   return (
      <main className={styles.container}>
         <Head>
            <title>Seyfettin Baskara</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Preview />
      </main>
   )
}

export default Home
